remote_theme: just-the-docs/just-the-docs

title: Apasita Pasukree
description: "จากคำถามเรื่องรถ สู่การวิเคราะห์ข้อมูลอุบัติเหตุ 80,621 ราย"

plugins:
  - jekyll-remote-theme

nav_sort: order

footer_content: "Huachiew Chalermprakiet University · Data+ Course Assignment"
